Feat(web)/o-search
VC-Team/yemusic pull request #55
Opened 2022-04-10 09:20 UTC by HaiGentle

Hi Mr. @thaihoanganh, help me to review this commit, please.
Thank !

2022-04-10 10:25 UTC, gialynguyen commented
closes #55

2022-04-12 02:18 UTC, thaihoanganh commented on apps/web/src/components/organisms/Search/SearchResultList.tsx
> +    <div className="result-list">
You should update again class name follows the ABEM standard.
See more:
- https://css-tricks.com/abem-useful-adaptation-bem
- https://github.com/VC-Team/yemusic/tree/develop/apps/web/src/components/molecules/Nav

2022-04-12 02:18 UTC, thaihoanganh commented on apps/web/src/components/organisms/Search/SearchResultListItem.tsx
> +    </div>
You should use only one modifier class in the root class of component

```scss
$root: atomic-block;

.#{$root} {
  &.-loading {
    .#{$root}__element {
    // Overwrite styles of element class here
    }
  }

  &__element {
  ...
  }
}
```

2022-04-12 02:18 UTC, thaihoanganh commented on apps/web/src/components/organisms/Search/styles.scss
> +  width: 280px;
The width should is auto, we should not use a fixed width for this component, a parent that uses this component will regulate the width for it. If it's a block element, you can remove the width style.

2022-04-12 02:18 UTC, thaihoanganh commented on apps/web/src/components/organisms/Search/styles.scss
> +  padding: 0.5rem;
I created a function is `pxtorem` in _function.scss, with padding and margin you should use this function for property value.

Example: `padding: pxtorem(8)`

2022-04-12 11:08 UTC, thaihoanganh requested changes

2022-04-12 11:08 UTC, thaihoanganh commented on apps/web/src/components/organisms/Search/styles.scss
> +  .result-list {
You should define the class name following the ABEM standard for root component and sub-component.

```scss
Search => o-search
SearchInput => o-search__input
SearchResultList => o-search__resultlist
SearchResultListItem  => o-search__resultlist__item
```

2022-04-17 08:17 UTC, HaiGentle commented on apps/web/src/components/organisms/Search/SearchInput.tsx
> +  onFocus?: (e?: React.FocusEvent<HTMLInputElement, Element> | undefined) => void;
![image](https://user-images.githubusercontent.com/70798976/163706470-a86eb9c2-0222-4a58-b369-547acdc35623.png)
Oh, I think they are not overwriten, because `...otherProps` has no  `onBlur` and `onFocus`

2022-04-17 09:09 UTC, HaiGentle commented on apps/web/src/components/organisms/Search/styles.scss
> +  .result-list {
if we have so  many children components, should we define "o-block__element__element__element"?

2022-04-22 10:54 UTC, thaihoanganh commented
@HaiGentle I have created an example [here](https://codesandbox.io/s/fast-fog-49zlb9) for my solution, help me review this.

2022-04-27 03:53 UTC, gialynguyen commented
@HaiGentle any updates?

2022-05-15 06:35 UTC, gialynguyen commented
@thaihoanganh review this

2022-05-20 13:54 UTC, gialynguyen commented
@thaihoanganh Review this

2022-05-25 16:35 UTC, merged