:sparkles: feat(utils): Implement function handler try catch
VC-Team/yemusic pull request #60
Opened 2022-04-13 00:39 UTC by trungpham71198

Closes #59

2022-04-13 00:57 UTC, khoaquocngo commented on apps/server/src/datasources/controllers/user/mutation.ts
> +import { useHandler } from '../../utils';
useHandler to global.useHandler. How do you think?

2022-04-13 02:04 UTC, gialynguyen commented on apps/server/src/datasources/controllers/user/mutation.ts
> +import { useHandler } from '../../utils';
I don't think this is a good idea. Instead, we could config the alias path to make the import paths brief.

2022-04-13 02:06 UTC, gialynguyen requested changes

2022-04-13 02:06 UTC, gialynguyen commented on apps/server/src/datasources/utils/useHandler.ts
> +export function useHandler(fn: (req: Request, res: Response, next: NextFunction) => Promise<Response>) {
Its name should be `useHttpHandler` to be more meaningful.

2022-04-14 16:29 UTC, gialynguyen commented
Blocked by #64

2022-04-17 08:20 UTC, khoaquocngo approved these changes

2022-04-17 09:05 UTC, trungpham71198 commented
> 

@gialynguyen done! Blocked by #64

2022-04-17 09:09 UTC, gialynguyen approved these changes

2022-04-17 09:09 UTC, merged